JBIDE-27667: Add browser based login
jbosstools/jbosstools-openshift pull request #1984
Opened 2021-03-08 07:06 UTC by jeffmaury

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

2021-03-08 09:35 UTC, sbouchet requested changes

2021-03-08 09:35 UTC, sbouchet commented on plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/LoginWizardPage.java
> +        txtToken.setText(OCCommandUtils.getServer(clipboardText));
please fix issue when pasting login command: 
```suggestion
        txtToken.setText(OCCommandUtils.getToken(clipboardText));
```

2021-03-08 13:29 UTC, sbouchet approved these changes
CDK Unit Test should be fixed, maybe on a separate JIRA. otherwise, LGTM.

2021-03-08 13:30 UTC, jeffmaury commented
I don't get why the CDK test are failing where master builds are ok ?

2021-03-09 14:11 UTC, jeffmaury commented
testPR

2021-03-10 16:48 UTC, jeffmaury commented
testPR

2021-03-10 17:25 UTC, merged