JBIDE-28571, update to itests, updating EAP 7.4 templates
jbosstools/jbosstools-openshift pull request #2092
Opened 2022-10-03 11:06 UTC by odockal

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

2022-10-04 08:27 UTC, odockal commented
@olkornii Please review.

2022-10-04 08:59 UTC, olkornii commented on itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/CreateResourcesTest.java
> +//	@Test
Some disabled tests, check if its ok pls

2022-10-04 08:59 UTC, olkornii commented on itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/CreateResourcesTest.java
> +//	@Test
Some disabled tests, check if its ok pls

2022-10-04 08:59 UTC, olkornii commented on itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CRCAllTestsSuite.java
> +//	CRCRuntimeDetectionTest.class,
Some disabled tests, check if its ok pls

2022-10-04 08:59 UTC, olkornii commented on itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
> +//	@Test
Some disabled tests, check if its ok pls

2022-10-04 08:59 UTC, olkornii commented on itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
> +//	@Test
Some disabled tests, check if its ok pls

2022-10-18 12:21 UTC, olkornii requested changes

2022-10-18 12:21 UTC, olkornii commented on itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/InteligentDeleteResourceTest.java
> +	public void testDeleteeReplicationController() {
"...Deletee", mb typo?

2022-10-18 12:21 UTC, olkornii commented on itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/DebugVertxDevfileComponentODOTest.java
> +@RequiredODOProject(name="test-project5", cleanup=true)
"name = "test-project5", cleanup = true" looks better

2022-10-18 13:03 UTC, odockal commented
@olkornii ready.

2022-10-18 13:27 UTC, olkornii approved these changes
LGTM

2022-10-19 10:01 UTC, olkornii approved these changes

2022-10-19 10:57 UTC, olkornii approved these changes

2022-10-19 12:31 UTC, sbouchet approved these changes
LGTM

2022-10-20 11:59 UTC, merged